/* AUTO-GENERATED by tools/generate_deck.py from the physical Civil Unrest deck. */
window.CU_CARDS = {
 "categories": {
  "green": {
   "name": "Economic Pressure",
   "sub": "Debt Crisis · Inflation · Labor Strikes",
   "color": "#7ab490"
  },
  "yellow": {
   "name": "Natural Disasters & Climate",
   "sub": "Hurricane · Wildfire · Drought",
   "color": "#f0e06a"
  },
  "blue": {
   "name": "Civil Discord & Identity",
   "sub": "Mass Protest · Censorship · Ethnic Tension",
   "color": "#5690a3"
  },
  "purple": {
   "name": "Global Influence & Interference",
   "sub": "Proxy War · Sanctions · Cyberattack",
   "color": "#800080"
  },
  "orange": {
   "name": "Demographics & Immigration",
   "sub": "Refugee Wave · Aging Population · Brain Drain",
   "color": "#f7a541"
  },
  "red": {
   "name": "Reform & Resource Tokens",
   "sub": "Used to reduce unrest or reform",
   "color": "#b73a28"
  },
  "black": {
   "name": "Civil Unrest",
   "sub": "America expansion · drawn on fist spaces",
   "color": "#1b1a15"
  }
 },
 "decks": {
  "green": [
   {
    "id": "green-0",
    "category": "green",
    "text": "Unemployment hits 10% as markets contract.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-1",
    "category": "green",
    "text": "Government defaults on international loans.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-2",
    "category": "green",
    "text": "Stock market enters prolonged bear phase.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-3",
    "category": "green",
    "text": "Consumer confidence falls to record low.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-4",
    "category": "green",
    "text": "Crypto crash eliminates retirement savings.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-5",
    "category": "green",
    "text": "Black market outpaces official currency.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-6",
    "category": "green",
    "text": "Currency faces speculative attack.",
    "instruction": "(x2 multiplier)",
    "type": "mult",
    "mult": 2.0
   },
   {
    "id": "green-7",
    "category": "green",
    "text": "Speculators flee market over corruption probe.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-8",
    "category": "green",
    "text": "Widespread layoffs in tech and finance.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-9",
    "category": "green",
    "text": "Major bank requires emergency bailout.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-10",
    "category": "green",
    "text": "Housing bubble inflates past 2008 levels.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-11",
    "category": "green",
    "text": "Basic goods experience hyperinflation.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-12",
    "category": "green",
    "text": "Subsidies end, raising cost of living.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-13",
    "category": "green",
    "text": "Blackouts halt industrial production for weeks.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-14",
    "category": "green",
    "text": "Stock buybacks banned to stabilize equity markets.",
    "instruction": "(x2 multiplier)",
    "type": "mult",
    "mult": 2.0
   },
   {
    "id": "green-15",
    "category": "green",
    "text": "Public pensions are slashed to balance budget.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-16",
    "category": "green",
    "text": "Workers demand 4-day workweek in mass strikes.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-17",
    "category": "green",
    "text": "Gig workers strike against AI scheduling.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-18",
    "category": "green",
    "text": "Cryptocurrency adoption spikes amid fiat instability.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-19",
    "category": "green",
    "text": "Debt-to-GDP ratio reaches unsustainable level.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-20",
    "category": "green",
    "text": "Housing market is frozen as interest rates surge.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-21",
    "category": "green",
    "text": "Import taxes cripple small businesses.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-22",
    "category": "green",
    "text": "Pension funds gamble and fail.",
    "instruction": "(+-4)",
    "type": "add",
    "add": -4
   },
   {
    "id": "green-23",
    "category": "green",
    "text": "Basic goods are hoarded, worsening shortages.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-24",
    "category": "green",
    "text": "Wage stagnation leads to increased borrowing.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-25",
    "category": "green",
    "text": "Public sector workers strike en masse.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-26",
    "category": "green",
    "text": "Shadow banking sector exposed in scandal.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-27",
    "category": "green",
    "text": "Trade deficit hits record high.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-28",
    "category": "green",
    "text": "Public sector workers strike en masse.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-29",
    "category": "green",
    "text": "Trade deficit hits record high.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-30",
    "category": "green",
    "text": "Basic goods are hoarded, worsening shortages.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-31",
    "category": "green",
    "text": "Debt-to-GDP ratio reaches unsustainable level.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-32",
    "category": "green",
    "text": "Major bank nationalized after liquidity crisis.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-33",
    "category": "green",
    "text": "Shadow banking sector exposed in scandal.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-34",
    "category": "green",
    "text": "Wage stagnation leads to increased borrowing.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-35",
    "category": "green",
    "text": "Housing market is frozen as interest rates surge.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-36",
    "category": "green",
    "text": "Bank run causes regional collapse.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-37",
    "category": "green",
    "text": "Tariffs imposed on critical raw materials.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-38",
    "category": "green",
    "text": "Mass boycott triggered by international trade dispute.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-39",
    "category": "green",
    "text": "Nation defaults on Belt and Road loan.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-40",
    "category": "green",
    "text": "Workers protest foreign corporate takeovers.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-41",
    "category": "green",
    "text": "Rural banks collapse under debt burden.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-42",
    "category": "green",
    "text": "Artificial inflation sparks calls for currency reform.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-43",
    "category": "green",
    "text": "Trade pact revoked, markets destabilize.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-44",
    "category": "green",
    "text": "Price controls cause black market to flourish.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-45",
    "category": "green",
    "text": "Central bank raises interest rates aggressively to contain inflation.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-46",
    "category": "green",
    "text": "Major hedge fund collapses, triggering credit panic.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-47",
    "category": "green",
    "text": "Consumer spending drops after energy prices surge.",
    "instruction": "(x1.5 multiplier)",
    "type": "mult",
    "mult": 1.5
   },
   {
    "id": "green-48",
    "category": "green",
    "text": "Real estate values plummet following debt overextension.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "green-49",
    "category": "green",
    "text": "Labor unions call for general strike over stagnant wages.",
    "instruction": "(Use Card Value)",
    "type": "space"
   }
  ],
  "yellow": [
   {
    "id": "yellow-0",
    "category": "yellow",
    "text": "Nuclear power meltdown leads to evacuation.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-1",
    "category": "yellow",
    "text": "Earthquake devastates historic region.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-2",
    "category": "yellow",
    "text": "Extreme heatwave shuts down industry.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-3",
    "category": "yellow",
    "text": "Coastal city abandoned due to sea rise.",
    "instruction": "(+-5)",
    "type": "add",
    "add": -5
   },
   {
    "id": "yellow-4",
    "category": "yellow",
    "text": "Polar vortex cripples power grid.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-5",
    "category": "yellow",
    "text": "Dust storms choke food supply lines.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-6",
    "category": "yellow",
    "text": "Heavy monsoon floods displace thousands.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-7",
    "category": "yellow",
    "text": "Tornado supercluster tears through Midwest.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-8",
    "category": "yellow",
    "text": "Environmental refugees overwhelm nearby cities.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-9",
    "category": "yellow",
    "text": "Nation faces year without a summer.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-10",
    "category": "yellow",
    "text": "Ecosystem collapse reduces biodiversity.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-11",
    "category": "yellow",
    "text": "Arctic thaw releases ancient viruses.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-12",
    "category": "yellow",
    "text": "Ice storm traps millions indoors.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-13",
    "category": "yellow",
    "text": "Freak hailstorm destroys millions in crops.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-14",
    "category": "yellow",
    "text": "Volcano eruption disrupts global air travel.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-15",
    "category": "yellow",
    "text": "Dust Bowl conditions return.",
    "instruction": "(+-5)",
    "type": "add",
    "add": -5
   },
   {
    "id": "yellow-16",
    "category": "yellow",
    "text": "Heat dome causes rolling blackouts.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-17",
    "category": "yellow",
    "text": "Locust swarms destroy harvests.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-18",
    "category": "yellow",
    "text": "Climate refugees flood border regions.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-19",
    "category": "yellow",
    "text": "Windstorm destroys solar farms.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-20",
    "category": "yellow",
    "text": "Crops rot due to sudden frost.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-21",
    "category": "yellow",
    "text": "Tsunami strikes densely populated coastline.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-22",
    "category": "yellow",
    "text": "Famine declared in drought-stricken region.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-23",
    "category": "yellow",
    "text": "Crops rot due to sudden frost.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-24",
    "category": "yellow",
    "text": "Climate refugees flood border regions.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-25",
    "category": "yellow",
    "text": "Tsunami strikes densely populated coastline.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-26",
    "category": "yellow",
    "text": "River dries up, devastating agriculture.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-27",
    "category": "yellow",
    "text": "Sandstorms halt supply convoys.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-28",
    "category": "yellow",
    "text": "Mudslides destroy mountain towns.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-29",
    "category": "yellow",
    "text": "Mudslides destroy mountain towns.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-30",
    "category": "yellow",
    "text": "Water crisis causes rationing and riots.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-31",
    "category": "yellow",
    "text": "Famine declared in drought-stricken region.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-32",
    "category": "yellow",
    "text": "Sandstorms halt supply convoys.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-33",
    "category": "yellow",
    "text": "Locust swarms destroy harvests.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-34",
    "category": "yellow",
    "text": "Water crisis causes rationing and riots.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-35",
    "category": "yellow",
    "text": "Nation loses crops to dust storms.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-36",
    "category": "yellow",
    "text": "Glacier collapse threatens hydroelectric dam.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-37",
    "category": "yellow",
    "text": "Environmental protests block fossil fuel terminals.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-38",
    "category": "yellow",
    "text": "Toxic waste spill poisons river systems.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-39",
    "category": "yellow",
    "text": "Fishery collapse disrupts global food chain.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-40",
    "category": "yellow",
    "text": "Extreme cold wave damages infrastructure.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-41",
    "category": "yellow",
    "text": "Category 5 hurricane devastates coastal region.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-42",
    "category": "yellow",
    "text": "Nationwide drought causes massive crop failure.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-43",
    "category": "yellow",
    "text": "Wildfires spread uncontrollably due to extreme heat.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-44",
    "category": "yellow",
    "text": "Global food shortage sparks international panic.",
    "instruction": "(x2 multiplier)",
    "type": "mult",
    "mult": 2.0
   },
   {
    "id": "yellow-45",
    "category": "yellow",
    "text": "Historic flooding submerges critical infrastructure.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-46",
    "category": "yellow",
    "text": "Category 5 hurricane devastates coastal region.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-47",
    "category": "yellow",
    "text": "Nationwide drought causes massive crop failure.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-48",
    "category": "yellow",
    "text": "Wildfires spread uncontrollably due to extreme heat.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "yellow-49",
    "category": "yellow",
    "text": "Global food shortage sparks international panic.",
    "instruction": "(x2 multiplier)",
    "type": "mult",
    "mult": 2.0
   }
  ],
  "blue": [
   {
    "id": "blue-0",
    "category": "blue",
    "text": "Mass shooting sparks gun reform protests.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-1",
    "category": "blue",
    "text": "Outlawed protest becomes national holiday.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-2",
    "category": "blue",
    "text": "State bans books on race and gender.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-3",
    "category": "blue",
    "text": "Hacktivist group leaks racial profiling database.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-4",
    "category": "blue",
    "text": "Students occupy government buildings.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-5",
    "category": "blue",
    "text": "Clashes erupt at pride parade.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-6",
    "category": "blue",
    "text": "Freedom of assembly suspended.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-7",
    "category": "blue",
    "text": "Religious law imposed in secular region.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-8",
    "category": "blue",
    "text": "Religious minority attacked during public holiday.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-9",
    "category": "blue",
    "text": "Conspiracy theories go viral online.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-10",
    "category": "blue",
    "text": "Political dissident disappears mysteriously.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-11",
    "category": "blue",
    "text": "Military refuses to intervene in civilian unrest.",
    "instruction": "(x1.5 multiplier)",
    "type": "mult",
    "mult": 1.5
   },
   {
    "id": "blue-12",
    "category": "blue",
    "text": "Cultural monument defaced during protest.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-13",
    "category": "blue",
    "text": "Banned political party wins underground support.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-14",
    "category": "blue",
    "text": "Transgender rights clash with religious law.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-15",
    "category": "blue",
    "text": "Hate crimes surge after controversial trial.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-16",
    "category": "blue",
    "text": "Journalists arrested during live broadcast.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-17",
    "category": "blue",
    "text": "Police shooting leads to racial unrest in major cities.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-18",
    "category": "blue",
    "text": "Protesters shut down major highways.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-19",
    "category": "blue",
    "text": "Protesters shut down major highways.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-20",
    "category": "blue",
    "text": "Journalist imprisoned for exposing corruption.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-21",
    "category": "blue",
    "text": "National anthem law sparks backlash.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-22",
    "category": "blue",
    "text": "Mass resignations from education sector.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-23",
    "category": "blue",
    "text": "Police unions walk out, creating chaos.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-24",
    "category": "blue",
    "text": "Paramilitary group patrols minority neighborhoods.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-25",
    "category": "blue",
    "text": "Gender laws divide the population.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-26",
    "category": "blue",
    "text": "Gender laws divide the population.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-27",
    "category": "blue",
    "text": "Urban areas declare autonomy from federal law.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-28",
    "category": "blue",
    "text": "Paramilitary group patrols minority neighborhoods.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-29",
    "category": "blue",
    "text": "Urban areas declare autonomy from federal law.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-30",
    "category": "blue",
    "text": "Student protests erupt over tuition hikes.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-31",
    "category": "blue",
    "text": "Student protests erupt over tuition hikes.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-32",
    "category": "blue",
    "text": "Mass resignations from education sector.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-33",
    "category": "blue",
    "text": "Police unions walk out, creating chaos.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-34",
    "category": "blue",
    "text": "Controversial bill passed in secret session.",
    "instruction": "(x2 multiplier)",
    "type": "mult",
    "mult": 2.0
   },
   {
    "id": "blue-35",
    "category": "blue",
    "text": "Aaron Swartz remembered as symbol of free knowledge.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-36",
    "category": "blue",
    "text": "Nationwide protests over government surveillance.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-37",
    "category": "blue",
    "text": "Public mourns whistleblower imprisoned for leaks.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-38",
    "category": "blue",
    "text": "Ross Ulbricht's case reignites debate on digital freedom.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-39",
    "category": "blue",
    "text": "Student journalists expose corruption scandal.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-40",
    "category": "blue",
    "text": "Banned social platform returns, sparking unrest.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-41",
    "category": "blue",
    "text": "Surveillance drone footage leaked by activist.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-42",
    "category": "blue",
    "text": "Unilateral curfew imposed after online dissent.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-43",
    "category": "blue",
    "text": "Religious minority attacked during public holiday.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-44",
    "category": "blue",
    "text": "Ethnic tensions flare as political party targets immigrants.",
    "instruction": "(x2 multiplier)",
    "type": "mult",
    "mult": 2.0
   },
   {
    "id": "blue-45",
    "category": "blue",
    "text": "Homosexual college student brutally murdered.",
    "instruction": "(Use Card Value)",
    "type": "space",
    "tribute": "Memory of Matthew Shepard"
   },
   {
    "id": "blue-46",
    "category": "blue",
    "text": "Censorship of online activists triggers mass protest.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-47",
    "category": "blue",
    "text": "Police shooting leads to racial unrest in major cities.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-48",
    "category": "blue",
    "text": "Religious minority attacked during public holiday.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "blue-49",
    "category": "blue",
    "text": "Ethnic tensions flare as political party targets immigrants.",
    "instruction": "(x2 multiplier)",
    "type": "mult",
    "mult": 2.0
   }
  ],
  "purple": [
   {
    "id": "purple-0",
    "category": "purple",
    "text": "Foreign nation funds domestic disinfo network.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-1",
    "category": "purple",
    "text": "UN issues sanctions over civil rights abuses.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-2",
    "category": "purple",
    "text": "Trade deal collapses amid trust breakdown.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-3",
    "category": "purple",
    "text": "Espionage scandal rocks diplomatic ties.",
    "instruction": "(x1.5 multiplier)",
    "type": "mult",
    "mult": 1.5
   },
   {
    "id": "purple-4",
    "category": "purple",
    "text": "Military base compromised by drone strike.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-5",
    "category": "purple",
    "text": "Foreign leader assassinated by rogue state.",
    "instruction": "(+-5)",
    "type": "add",
    "add": -5
   },
   {
    "id": "purple-6",
    "category": "purple",
    "text": "Diplomatic ties restored after hostage crisis.",
    "instruction": "(-1)",
    "type": "add",
    "add": -1
   },
   {
    "id": "purple-7",
    "category": "purple",
    "text": "Proxy war escalates in strategic border region.",
    "instruction": "(x2 multiplier)",
    "type": "mult",
    "mult": 2.0
   },
   {
    "id": "purple-8",
    "category": "purple",
    "text": "Space arms treaty collapses.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-9",
    "category": "purple",
    "text": "Nation joins rival military alliance.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-10",
    "category": "purple",
    "text": "Nation accused of ethnic cleansing by UN.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-11",
    "category": "purple",
    "text": "Spy satellite intercepted by rival nation.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-12",
    "category": "purple",
    "text": "Trade route blockade raises global prices.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-13",
    "category": "purple",
    "text": "Cyberattack disrupts banking infrastructure.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-14",
    "category": "purple",
    "text": "Top diplomat defects and releases tapes.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-15",
    "category": "purple",
    "text": "Border conflict draws in allies.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-16",
    "category": "purple",
    "text": "Border conflict draws in allies.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-17",
    "category": "purple",
    "text": "Overseas embassy stormed.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-18",
    "category": "purple",
    "text": "International watchdog exposes human rights abuses.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-19",
    "category": "purple",
    "text": "War games spark panic among neighbors.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-20",
    "category": "purple",
    "text": "Cyberattack disables water supply systems.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-21",
    "category": "purple",
    "text": "International watchdog exposes human rights abuses.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-22",
    "category": "purple",
    "text": "Fake summit misleads global markets.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-23",
    "category": "purple",
    "text": "Foreign aid cuts cause local unrest.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-24",
    "category": "purple",
    "text": "Foreign diplomats expelled for espionage.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-25",
    "category": "purple",
    "text": "Ambassador kidnapped in warzone.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-26",
    "category": "purple",
    "text": "Media broadcasts intercepted by foreign signal.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-27",
    "category": "purple",
    "text": "Foreign diplomats expelled for espionage.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-28",
    "category": "purple",
    "text": "Foreign aid cuts cause local unrest.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-29",
    "category": "purple",
    "text": "Nuclear treaty violation confirmed.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-30",
    "category": "purple",
    "text": "War games spark panic among neighbors.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-31",
    "category": "purple",
    "text": "Nuclear treaty violation confirmed.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-32",
    "category": "purple",
    "text": "Media broadcasts intercepted by foreign signal.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-33",
    "category": "purple",
    "text": "Cyberattack disables water supply systems.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-34",
    "category": "purple",
    "text": "Ally continues arms sales to nation committing genocide.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-35",
    "category": "purple",
    "text": "Country accused of shielding war criminals.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-36",
    "category": "purple",
    "text": "UN fails to pass ceasefire resolution.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-37",
    "category": "purple",
    "text": "Unilateralism isolates nation from allies.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-38",
    "category": "purple",
    "text": "Foreign leader visits embargoed nation.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-39",
    "category": "purple",
    "text": "Election interference confirmed via digital footprint.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-40",
    "category": "purple",
    "text": "Multinational summit collapses over climate dispute.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-41",
    "category": "purple",
    "text": "Leaked intelligence reveals cyber black ops.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-42",
    "category": "purple",
    "text": "Proxy war escalates in strategic border region.",
    "instruction": "(x2 multiplier)",
    "type": "mult",
    "mult": 2.0
   },
   {
    "id": "purple-43",
    "category": "purple",
    "text": "Allied nation imposes sanctions over civil rights abuses.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-44",
    "category": "purple",
    "text": "Fake news campaign destabilizes trust in media.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-45",
    "category": "purple",
    "text": "Whistleblower leaks surveillance documents.",
    "instruction": "(Use Card Value)",
    "type": "space",
    "tribute": "Thank You Edward Snowden"
   },
   {
    "id": "purple-46",
    "category": "purple",
    "text": "Foreign hackers breach electoral commission systems.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-47",
    "category": "purple",
    "text": "Proxy war escalates in strategic border region.",
    "instruction": "(x2 multiplier)",
    "type": "mult",
    "mult": 2.0
   },
   {
    "id": "purple-48",
    "category": "purple",
    "text": "Allied nation imposes sanctions over civil rights abuses.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-49",
    "category": "purple",
    "text": "Fake news campaign destabilizes trust in media.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "purple-50",
    "category": "purple",
    "text": "Foreign disinformation campaign targets opponent.",
    "instruction": "(Choose a player to gain +-3 unrest. You gain +-1 unrest)",
    "type": "targeted",
    "effect": {
     "action": "chooseGain",
     "target": -3,
     "self": -1
    }
   },
   {
    "id": "purple-51",
    "category": "purple",
    "text": "International aid package diverts focus.",
    "instruction": "(Remove 2 unrest from yourself, assign +-1 unrest to two other players)",
    "type": "targeted",
    "effect": {
     "action": "selfRemoveOthers",
     "self": -2,
     "others": -1,
     "count": 2
    }
   },
   {
    "id": "purple-52",
    "category": "purple",
    "text": "Global treaty bypasses national law.",
    "instruction": "(You gain +-2 unrest. One player of your choice loses 2 unrest)",
    "type": "targeted",
    "effect": {
     "action": "selfGainTargetLose",
     "self": -2,
     "target": -2
    }
   },
   {
    "id": "purple-53",
    "category": "purple",
    "text": "Foreign agent exposed in government.",
    "instruction": "(Swap unrest totals with a player within ±5 unrest points)",
    "type": "targeted",
    "effect": {
     "action": "swap",
     "within": 5
    }
   },
   {
    "id": "purple-54",
    "category": "purple",
    "text": "Proxy conflict spills over borders.",
    "instruction": "(All other players gain +-2 unrest)",
    "type": "targeted",
    "effect": {
     "action": "allOthers",
     "val": -2
    }
   },
   {
    "id": "purple-55",
    "category": "purple",
    "text": "Multinational scandal erodes trust.",
    "instruction": "(All players draw an extra Purple card on their next Purple space)",
    "type": "targeted",
    "effect": {
     "action": "nextPurpleExtra"
    }
   },
   {
    "id": "purple-56",
    "category": "purple",
    "text": "Cyberwar offensive redirected.",
    "instruction": "(Transfer your next Purple card effect to another player)",
    "type": "targeted",
    "effect": {
     "action": "transferPurple"
    }
   },
   {
    "id": "purple-57",
    "category": "purple",
    "text": "Espionage revelation sparks backlash.",
    "instruction": "(All players must discard one held card, if any)",
    "type": "targeted",
    "effect": {
     "action": "discardAll"
    }
   },
   {
    "id": "purple-58",
    "category": "purple",
    "text": "Surge in elderly population strains healthcare.",
    "instruction": "(Use Card Value)",
    "type": "space"
   }
  ],
  "orange": [
   {
    "id": "orange-0",
    "category": "orange",
    "text": "Foreign-born students dominate tech sector.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-1",
    "category": "orange",
    "text": "Baby bonus leads to birth rate rebound.",
    "instruction": "(-1)",
    "type": "add",
    "add": -1
   },
   {
    "id": "orange-2",
    "category": "orange",
    "text": "New citizenship law leads to protests.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-3",
    "category": "orange",
    "text": "Border wall collapses amid political scandal.",
    "instruction": "(x2 multiplier)",
    "type": "mult",
    "mult": 2.0
   },
   {
    "id": "orange-4",
    "category": "orange",
    "text": "Rural areas depopulate rapidly.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-5",
    "category": "orange",
    "text": "Population growth freezes, causing economic fears.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-6",
    "category": "orange",
    "text": "Aging population puts strain on pensions.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-7",
    "category": "orange",
    "text": "Brain drain accelerates as skilled workers leave.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-8",
    "category": "orange",
    "text": "Refugee wave overwhelms border control systems.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-9",
    "category": "orange",
    "text": "New law revokes citizenship for foreign-born residents.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-10",
    "category": "orange",
    "text": "Tech jobs attract massive immigration wave.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-11",
    "category": "orange",
    "text": "Rural exodus leaves farmland unworked.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-12",
    "category": "orange",
    "text": "New law revokes citizenship for foreign-born residents.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-13",
    "category": "orange",
    "text": "Populist party campaigns on ethnic purity.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-14",
    "category": "orange",
    "text": "Fertility clinics shut down amid scandal.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-15",
    "category": "orange",
    "text": "Family size restrictions met with resistance.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-16",
    "category": "orange",
    "text": "Protesters oppose refugee housing in suburbs.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-17",
    "category": "orange",
    "text": "Ban on foreign languages in schools.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-18",
    "category": "orange",
    "text": "Rural exodus leaves farmland unworked.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-19",
    "category": "orange",
    "text": "Mass deportations provoke international outcry.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-20",
    "category": "orange",
    "text": "Foreign students denied graduation visas.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-21",
    "category": "orange",
    "text": "Border state declares emergency.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-22",
    "category": "orange",
    "text": "Climate migration overwhelms border towns.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-23",
    "category": "orange",
    "text": "Immigrant detention centers overflow.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-24",
    "category": "orange",
    "text": "Birth rates collapse in tech-heavy cities.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-25",
    "category": "orange",
    "text": "National ID law stirs ethnic backlash.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-26",
    "category": "orange",
    "text": "Refugee children denied access to public schools.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-27",
    "category": "orange",
    "text": "Military deployed to border for optics.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-28",
    "category": "orange",
    "text": "Refugee wave overwhelms border control systems.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-29",
    "category": "orange",
    "text": "Fertility rate drops below replacement level.",
    "instruction": "(x1.5 multiplier)",
    "type": "mult",
    "mult": 1.5
   },
   {
    "id": "orange-30",
    "category": "orange",
    "text": "Rising nationalism sparks anti-immigration legislation.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-31",
    "category": "orange",
    "text": "Aging population puts strain on pensions.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-32",
    "category": "orange",
    "text": "Brain drain accelerates as skilled workers leave.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-33",
    "category": "orange",
    "text": "Refugee wave overwhelms border control systems.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-34",
    "category": "orange",
    "text": "Fertility rate drops below replacement level.",
    "instruction": "(x1.5 multiplier)",
    "type": "mult",
    "mult": 1.5
   },
   {
    "id": "orange-35",
    "category": "orange",
    "text": "Rising nationalism sparks anti-immigration legislation.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-36",
    "category": "orange",
    "text": "Aging population puts strain on pensions.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-37",
    "category": "orange",
    "text": "Brain drain accelerates as skilled workers leave.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-38",
    "category": "orange",
    "text": "Refugee wave overwhelms border control systems.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-39",
    "category": "orange",
    "text": "Fertility rate drops below replacement level.",
    "instruction": "(x1.5 multiplier)",
    "type": "mult",
    "mult": 1.5
   },
   {
    "id": "orange-40",
    "category": "orange",
    "text": "Rising nationalism sparks anti-immigration legislation.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-41",
    "category": "orange",
    "text": "Public schools close due to low birth rate.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-42",
    "category": "orange",
    "text": "Family reunification policy causes political split.",
    "instruction": "(x1.5 multiplier)",
    "type": "mult",
    "mult": 1.5
   },
   {
    "id": "orange-43",
    "category": "orange",
    "text": "Cultural festival banned by nationalist law.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-44",
    "category": "orange",
    "text": "National census reveals ethnic imbalance.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-45",
    "category": "orange",
    "text": "Mass emigration strains education system.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-46",
    "category": "orange",
    "text": "Tech sector hires thousands of foreign workers.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-47",
    "category": "orange",
    "text": "Immigrant labor force boycotts for fair wages.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-48",
    "category": "orange",
    "text": "Refugee wave overwhelms border control systems.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-49",
    "category": "orange",
    "text": "Surge in elderly population strains healthcare.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-50",
    "category": "orange",
    "text": "Foreign-born students dominate tech sector.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-51",
    "category": "orange",
    "text": "Baby bonus leads to birth rate rebound.",
    "instruction": "(-1)",
    "type": "add",
    "add": -1
   },
   {
    "id": "orange-52",
    "category": "orange",
    "text": "New citizenship law leads to protests.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-53",
    "category": "orange",
    "text": "Border wall collapses amid political scandal.",
    "instruction": "(x2 multiplier)",
    "type": "mult",
    "mult": 2.0
   },
   {
    "id": "orange-54",
    "category": "orange",
    "text": "Rural areas depopulate rapidly.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-55",
    "category": "orange",
    "text": "Population growth freezes, causing economic fears.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-56",
    "category": "orange",
    "text": "Aging population puts strain on pensions.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-57",
    "category": "orange",
    "text": "Brain drain accelerates as skilled workers leave.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-58",
    "category": "orange",
    "text": "Refugee wave overwhelms border control systems.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-59",
    "category": "orange",
    "text": "New law revokes citizenship for foreign-born residents.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-60",
    "category": "orange",
    "text": "Tech jobs attract massive immigration wave.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-61",
    "category": "orange",
    "text": "Rural exodus leaves farmland unworked.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-62",
    "category": "orange",
    "text": "New law revokes citizenship for foreign-born residents.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-63",
    "category": "orange",
    "text": "Populist party campaigns on ethnic purity.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-64",
    "category": "orange",
    "text": "Fertility clinics shut down amid scandal.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-65",
    "category": "orange",
    "text": "Family size restrictions met with resistance.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-66",
    "category": "orange",
    "text": "Protesters oppose refugee housing in suburbs.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-67",
    "category": "orange",
    "text": "Ban on foreign languages in schools.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-68",
    "category": "orange",
    "text": "Rural exodus leaves farmland unworked.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-69",
    "category": "orange",
    "text": "Mass deportations provoke international outcry.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-70",
    "category": "orange",
    "text": "Foreign students denied graduation visas.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-71",
    "category": "orange",
    "text": "Border state declares emergency.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-72",
    "category": "orange",
    "text": "Climate migration overwhelms border towns.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-73",
    "category": "orange",
    "text": "Immigrant detention centers overflow.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-74",
    "category": "orange",
    "text": "Birth rates collapse in tech-heavy cities.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-75",
    "category": "orange",
    "text": "National ID law stirs ethnic backlash.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-76",
    "category": "orange",
    "text": "Refugee children denied access to public schools.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-77",
    "category": "orange",
    "text": "Military deployed to border for optics.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-78",
    "category": "orange",
    "text": "Refugee wave overwhelms border control systems.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-79",
    "category": "orange",
    "text": "Fertility rate drops below replacement level.",
    "instruction": "(x1.5 multiplier)",
    "type": "mult",
    "mult": 1.5
   },
   {
    "id": "orange-80",
    "category": "orange",
    "text": "Rising nationalism sparks anti-immigration legislation.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-81",
    "category": "orange",
    "text": "Aging population puts strain on pensions.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-82",
    "category": "orange",
    "text": "Brain drain accelerates as skilled workers leave.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-83",
    "category": "orange",
    "text": "Refugee wave overwhelms border control systems.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-84",
    "category": "orange",
    "text": "Fertility rate drops below replacement level.",
    "instruction": "(x1.5 multiplier)",
    "type": "mult",
    "mult": 1.5
   },
   {
    "id": "orange-85",
    "category": "orange",
    "text": "Rising nationalism sparks anti-immigration legislation.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-86",
    "category": "orange",
    "text": "Aging population puts strain on pensions.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-87",
    "category": "orange",
    "text": "Brain drain accelerates as skilled workers leave.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-88",
    "category": "orange",
    "text": "Refugee wave overwhelms border control systems.",
    "instruction": "(Use Card Value)",
    "type": "space"
   },
   {
    "id": "orange-89",
    "category": "orange",
    "text": "Fertility rate drops below replacement level.",
    "instruction": "(x1.5 multiplier)",
    "type": "mult",
    "mult": 1.5
   },
   {
    "id": "orange-90",
    "category": "orange",
    "text": "Rising nationalism sparks anti-immigration legislation.",
    "instruction": "(Use Card Value)",
    "type": "space"
   }
  ],
  "red": [
   {
    "id": "red-0",
    "category": "red",
    "text": "Medical innovation reduces public fear.",
    "instruction": "(-2)",
    "type": "add",
    "add": -2
   },
   {
    "id": "red-1",
    "category": "red",
    "text": "Social media literacy campaign strengthens trust.",
    "instruction": "(-1)",
    "type": "add",
    "add": -1
   },
   {
    "id": "red-2",
    "category": "red",
    "text": "Peace accord signed after decades of unrest.",
    "instruction": "(-3)",
    "type": "add",
    "add": -3
   },
   {
    "id": "red-3",
    "category": "red",
    "text": "National broadband initiative boosts access.",
    "instruction": "(-1)",
    "type": "add",
    "add": -1
   },
   {
    "id": "red-4",
    "category": "red",
    "text": "Universal healthcare rollout restores stability.",
    "instruction": "(-2)",
    "type": "add",
    "add": -2
   },
   {
    "id": "red-5",
    "category": "red",
    "text": "Community housing cuts urban tension.",
    "instruction": "(-3)",
    "type": "add",
    "add": -3
   },
   {
    "id": "red-6",
    "category": "red",
    "text": "Reforestation campaign improves climate morale.",
    "instruction": "(-2)",
    "type": "add",
    "add": -2
   },
   {
    "id": "red-7",
    "category": "red",
    "text": "Public transport becomes free in urban areas.",
    "instruction": "(-2)",
    "type": "add",
    "add": -2
   },
   {
    "id": "red-8",
    "category": "red",
    "text": "Community gardens improve food security.",
    "instruction": "(-2)",
    "type": "add",
    "add": -2
   },
   {
    "id": "red-9",
    "category": "red",
    "text": "Whistleblower protections increase trust in government.",
    "instruction": "(-1)",
    "type": "add",
    "add": -1
   },
   {
    "id": "red-10",
    "category": "red",
    "text": "Vaccination campaign restores health infrastructure.",
    "instruction": "(-2)",
    "type": "add",
    "add": -2
   },
   {
    "id": "red-11",
    "category": "red",
    "text": "Solar energy adoption reaches 50% nationwide.",
    "instruction": "(-2)",
    "type": "add",
    "add": -2
   },
   {
    "id": "red-12",
    "category": "red",
    "text": "Digital currency pilot increases financial inclusion.",
    "instruction": "(-1)",
    "type": "add",
    "add": -1
   },
   {
    "id": "red-13",
    "category": "red",
    "text": "Tech literacy training expands public access.",
    "instruction": "(-1)",
    "type": "add",
    "add": -1
   },
   {
    "id": "red-14",
    "category": "red",
    "text": "Mental health funding reduces crime.",
    "instruction": "(-2)",
    "type": "add",
    "add": -2
   },
   {
    "id": "red-15",
    "category": "red",
    "text": "Worker-owned businesses gain popularity.",
    "instruction": "(-2)",
    "type": "add",
    "add": -2
   },
   {
    "id": "red-16",
    "category": "red",
    "text": "Fact-checking system earns national trust.",
    "instruction": "(-1)",
    "type": "add",
    "add": -1
   },
   {
    "id": "red-17",
    "category": "red",
    "text": "Language inclusion program bridges divides.",
    "instruction": "(-2)",
    "type": "add",
    "add": -2
   },
   {
    "id": "red-18",
    "category": "red",
    "text": "Global education fund supports innovation.",
    "instruction": "(-1)",
    "type": "add",
    "add": -1
   },
   {
    "id": "red-19",
    "category": "red",
    "text": "Decentralized power grid increases resilience.",
    "instruction": "(-2)",
    "type": "add",
    "add": -2
   },
   {
    "id": "red-20",
    "category": "red",
    "text": "City cleanup campaign inspires youth.",
    "instruction": "(-1)",
    "type": "add",
    "add": -1
   },
   {
    "id": "red-21",
    "category": "red",
    "text": "Mobile clinics bring care to rural zones.",
    "instruction": "(-2)",
    "type": "add",
    "add": -2
   },
   {
    "id": "red-22",
    "category": "red",
    "text": "Open source transparency platform launched.",
    "instruction": "(-1)",
    "type": "add",
    "add": -1
   },
   {
    "id": "red-23",
    "category": "red",
    "text": "Water purification kits save lives.",
    "instruction": "(-2)",
    "type": "add",
    "add": -2
   },
   {
    "id": "red-24",
    "category": "red",
    "text": "Farm co-ops feed displaced populations.",
    "instruction": "(-3)",
    "type": "add",
    "add": -3
   },
   {
    "id": "red-25",
    "category": "red",
    "text": "Restorative justice program reduces prison population.",
    "instruction": "(-2)",
    "type": "add",
    "add": -2
   },
   {
    "id": "red-26",
    "category": "red",
    "text": "Civil liberties bill passes amid unrest.",
    "instruction": "(-1)",
    "type": "add",
    "add": -1
   },
   {
    "id": "red-27",
    "category": "red",
    "text": "Open data initiative increases transparency.",
    "instruction": "(-2)",
    "type": "add",
    "add": -2
   },
   {
    "id": "red-28",
    "category": "red",
    "text": "Human rights watchdog granted oversight powers.",
    "instruction": "(-2)",
    "type": "add",
    "add": -2
   },
   {
    "id": "red-29",
    "category": "red",
    "text": "Post-conflict truth commission fosters healing.",
    "instruction": "(-3)",
    "type": "add",
    "add": -3
   },
   {
    "id": "red-30",
    "category": "red",
    "text": "Youth climate program gets national funding.",
    "instruction": "(-2)",
    "type": "add",
    "add": -2
   },
   {
    "id": "red-31",
    "category": "red",
    "text": "Civic tech platform empowers local communities.",
    "instruction": "(-1)",
    "type": "add",
    "add": -1
   },
   {
    "id": "red-32",
    "category": "red",
    "text": "Decentralized governance model piloted.",
    "instruction": "(-2)",
    "type": "add",
    "add": -2
   },
   {
    "id": "red-33",
    "category": "red",
    "text": "Cross-party agreement strengthens public trust.",
    "instruction": "(-2)",
    "type": "add",
    "add": -2
   },
   {
    "id": "red-34",
    "category": "red",
    "text": "Emergency powers allow rapid disaster response.",
    "instruction": "(-3)",
    "type": "add",
    "add": -3
   },
   {
    "id": "red-35",
    "category": "red",
    "text": "Population elects leaders promising austerity.",
    "instruction": "(x2 multiplier)",
    "type": "mult",
    "mult": 2.0
   },
   {
    "id": "red-36",
    "category": "red",
    "text": "Massive investment in green infrastructure.",
    "instruction": "(-2)",
    "type": "add",
    "add": -2
   },
   {
    "id": "red-37",
    "category": "red",
    "text": "Universal basic income pilot program gains support.",
    "instruction": "(-1)",
    "type": "add",
    "add": -1
   },
   {
    "id": "red-38",
    "category": "red",
    "text": "Cross-party agreement strengthens public trust.",
    "instruction": "(-2)",
    "type": "add",
    "add": -2
   },
   {
    "id": "red-39",
    "category": "red",
    "text": "Emergency powers allow rapid disaster response.",
    "instruction": "(-3)",
    "type": "add",
    "add": -3
   },
   {
    "id": "red-40",
    "category": "red",
    "text": "Population elects leaders promising austerity.",
    "instruction": "(x2 multiplier)",
    "type": "mult",
    "mult": 2.0
   },
   {
    "id": "red-41",
    "category": "red",
    "text": "Massive investment in green infrastructure.",
    "instruction": "(-2)",
    "type": "add",
    "add": -2
   },
   {
    "id": "red-42",
    "category": "red",
    "text": "Universal basic income pilot program gains support.",
    "instruction": "(-1)",
    "type": "add",
    "add": -1
   },
   {
    "id": "red-43",
    "category": "red",
    "text": "Cross-party agreement strengthens public trust.",
    "instruction": "(-2)",
    "type": "add",
    "add": -2
   },
   {
    "id": "red-44",
    "category": "red",
    "text": "Emergency powers allow rapid disaster response.",
    "instruction": "(-3)",
    "type": "add",
    "add": -3
   },
   {
    "id": "red-45",
    "category": "red",
    "text": "Population elects leaders promising austerity.",
    "instruction": "(x2 multiplier)",
    "type": "mult",
    "mult": 2.0
   },
   {
    "id": "red-46",
    "category": "red",
    "text": "Massive investment in green infrastructure.",
    "instruction": "(-2)",
    "type": "add",
    "add": -2
   },
   {
    "id": "red-47",
    "category": "red",
    "text": "Universal basic income pilot program gains support.",
    "instruction": "(-1)",
    "type": "add",
    "add": -1
   },
   {
    "id": "red-48",
    "category": "red",
    "text": "Cross-party agreement strengthens public trust.",
    "instruction": "(-2)",
    "type": "add",
    "add": -2
   },
   {
    "id": "red-49",
    "category": "red",
    "text": "Emergency powers allow rapid disaster response.",
    "instruction": "(-3)",
    "type": "add",
    "add": -3
   },
   {
    "id": "red-50",
    "category": "red",
    "text": "Public sector pay freeze approved.",
    "instruction": "(Reduce unrest by 4)",
    "type": "reduce",
    "reduce": 4
   },
   {
    "id": "red-51",
    "category": "red",
    "text": "Landmark infrastructure bill passed.",
    "instruction": "(Reduce unrest by 6; hold and play on a future turn)",
    "type": "reduce",
    "reduce": 6,
    "hold": true
   },
   {
    "id": "red-52",
    "category": "red",
    "text": "Debt restructuring deal signed.",
    "instruction": "(Reduce unrest by 5)",
    "type": "reduce",
    "reduce": 5
   },
   {
    "id": "red-53",
    "category": "red",
    "text": "National unity movement gains momentum.",
    "instruction": "(Reduce unrest by 7)",
    "type": "reduce",
    "reduce": 7
   },
   {
    "id": "red-54",
    "category": "red",
    "text": "Election Reform Act implemented.",
    "instruction": "(Hold for 3 turns to reduce unrest by 8, or play immediately for 3)",
    "type": "election",
    "reduce": 3,
    "reduce_held": 8,
    "hold": true
   },
   {
    "id": "red-55",
    "category": "red",
    "text": "Universal basic services piloted.",
    "instruction": "(Reduce unrest by 4)",
    "type": "reduce",
    "reduce": 4
   },
   {
    "id": "red-56",
    "category": "red",
    "text": "Whistleblower protections strengthened.",
    "instruction": "(Reduce unrest by 2)",
    "type": "reduce",
    "reduce": 2
   },
   {
    "id": "red-57",
    "category": "red",
    "text": "Emergency budget restores trust.",
    "instruction": "(Reduce unrest by 5)",
    "type": "reduce",
    "reduce": 5
   }
  ]
 }
};
