/* AUTO-GENERATED by tools/generate_deck.py from the Civil Unrest: America expansion (USA.xlsx). */
window.CU_AMERICA = {
 "decks": {
  "green": [
   {
    "id": "green-0",
    "category": "green",
    "text": "Prolonged shutdown delays federal pay; protests at airports.",
    "instruction": "(+-4)",
    "type": "add",
    "expansion": "america",
    "add": -4
   },
   {
    "id": "green-1",
    "category": "green",
    "text": "Tariff surge raises prices; truckers blockade a port.",
    "instruction": "(Use Card Value)",
    "type": "space",
    "expansion": "america"
   },
   {
    "id": "green-2",
    "category": "green",
    "text": "Debt ceiling standoff spooks markets; pensions wobble.",
    "instruction": "(+-5)",
    "type": "add",
    "expansion": "america",
    "add": -5
   },
   {
    "id": "green-3",
    "category": "green",
    "text": "Supply chain protests over new trade rules stall shipments.",
    "instruction": "(Reduce unrest by 5)",
    "type": "reduce",
    "expansion": "america",
    "reduce": 5
   },
   {
    "id": "green-4",
    "category": "green",
    "text": "Corporate PACs freeze donations amid political turmoil.",
    "instruction": "(You gain +-2 unrest. One player of your choice loses 2 unrest)",
    "type": "targeted",
    "expansion": "america",
    "effect": {
     "action": "selfGainTargetLose",
     "self": -2,
     "target": -2
    }
   },
   {
    "id": "green-5",
    "category": "green",
    "text": "Union walkouts over politicized mandates spread nationwide.",
    "instruction": "(Use Card Value)",
    "type": "space",
    "expansion": "america"
   }
  ],
  "yellow": [],
  "blue": [
   {
    "id": "blue-0",
    "category": "blue",
    "text": "Viral falsehood fractures communities; debates turn into street clashes.",
    "instruction": "(+-4)",
    "type": "add",
    "expansion": "america",
    "add": -4
   },
   {
    "id": "blue-1",
    "category": "blue",
    "text": "Major platform bans incendiary accounts; shadow networks emerge.",
    "instruction": "(All other players gain +-2 unrest)",
    "type": "targeted",
    "expansion": "america",
    "effect": {
     "action": "allOthers",
     "val": -2
    }
   },
   {
    "id": "blue-2",
    "category": "blue",
    "text": "Culture-war boycott shuts down local events for weeks.",
    "instruction": "(Use Card Value)",
    "type": "space",
    "expansion": "america"
   },
   {
    "id": "blue-3",
    "category": "blue",
    "text": "Leaked audio of pressure campaign fuels national outrage.",
    "instruction": "(x2 multiplier)",
    "type": "mult",
    "expansion": "america",
    "mult": 2.0
   },
   {
    "id": "blue-4",
    "category": "blue",
    "text": "Families split over politics; neighborhood councils dissolve.",
    "instruction": "(Swap unrest totals with a player within ±5 unrest points)",
    "type": "targeted",
    "expansion": "america",
    "effect": {
     "action": "swap",
     "within": 5
    }
   },
   {
    "id": "blue-5",
    "category": "blue",
    "text": "Counter-protests collide after inflammatory speech.",
    "instruction": "(+-5)",
    "type": "add",
    "expansion": "america",
    "add": -5
   }
  ],
  "purple": [
   {
    "id": "purple-0",
    "category": "purple",
    "text": "Foreign actors amplify doubts about election integrity.",
    "instruction": "(All players draw an extra Purple card on their next Purple space)",
    "type": "targeted",
    "expansion": "america",
    "effect": {
     "action": "nextPurpleExtra"
    }
   },
   {
    "id": "purple-1",
    "category": "purple",
    "text": "Coordinated hack‑and‑leak targets local officials.",
    "instruction": "(+-4)",
    "type": "add",
    "expansion": "america",
    "add": -4
   },
   {
    "id": "purple-2",
    "category": "purple",
    "text": "Disinfo botnets trend slogans that inflame rallies.",
    "instruction": "(Transfer your next Purple card effect to another player)",
    "type": "targeted",
    "expansion": "america",
    "effect": {
     "action": "transferPurple"
    }
   },
   {
    "id": "purple-3",
    "category": "purple",
    "text": "State media highlights domestic unrest to undermine confidence.",
    "instruction": "(Use Card Value)",
    "type": "space",
    "expansion": "america"
   },
   {
    "id": "purple-4",
    "category": "purple",
    "text": "Backchannel promises surface; allies demand explanations.",
    "instruction": "(Reduce unrest by 2)",
    "type": "reduce",
    "expansion": "america",
    "reduce": 2
   },
   {
    "id": "purple-5",
    "category": "purple",
    "text": "Foreign funding to fringe groups uncovered.",
    "instruction": "(Choose a player to gain +-3 unrest. You gain +-1 unrest)",
    "type": "targeted",
    "expansion": "america",
    "effect": {
     "action": "chooseGain",
     "target": -3,
     "self": -1
    }
   }
  ],
  "orange": [
   {
    "id": "orange-0",
    "category": "orange",
    "text": "Mass arrests at border sparks dueling marches.",
    "instruction": "(+-4)",
    "type": "add",
    "expansion": "america",
    "add": -4
   },
   {
    "id": "orange-1",
    "category": "orange",
    "text": "Cities sue states over transport of migrants.",
    "instruction": "(Use Card Value)",
    "type": "space",
    "expansion": "america"
   },
   {
    "id": "orange-2",
    "category": "orange",
    "text": "National Guard deployment at border fuels standoff images.",
    "instruction": "(+-5)",
    "type": "add",
    "expansion": "america",
    "add": -5
   },
   {
    "id": "orange-3",
    "category": "orange",
    "text": "Court ruling on asylum triggers courthouse protests.",
    "instruction": "(Reduce unrest by 4)",
    "type": "reduce",
    "expansion": "america",
    "reduce": 4
   },
   {
    "id": "orange-4",
    "category": "orange",
    "text": "Sheriffs defy federal guidance, creating patchwork enforcement.",
    "instruction": "(Swap unrest totals with a player within ±5 unrest points)",
    "type": "targeted",
    "expansion": "america",
    "effect": {
     "action": "swap",
     "within": 5
    }
   },
   {
    "id": "orange-5",
    "category": "orange",
    "text": "Sanctuary policy referendum becomes flashpoint.",
    "instruction": "(x1.5 multiplier)",
    "type": "mult",
    "expansion": "america",
    "mult": 1.5
   }
  ],
  "red": [
   {
    "id": "red-0",
    "category": "red",
    "text": "Attempt to invalidate certified results triggers constitutional crisis.",
    "instruction": "(Use Card Value)",
    "type": "space",
    "expansion": "america"
   },
   {
    "id": "red-1",
    "category": "red",
    "text": "Coordinated pressure on state officials to alter counts is exposed.",
    "instruction": "(+-4)",
    "type": "add",
    "expansion": "america",
    "add": -4
   },
   {
    "id": "red-2",
    "category": "red",
    "text": "Senior aides resign en masse after norm‑breaking directive.",
    "instruction": "(+-5)",
    "type": "add",
    "expansion": "america",
    "add": -5
   },
   {
    "id": "red-3",
    "category": "red",
    "text": "Electors face intimidation; emergency hearings convened.",
    "instruction": "(Reduce unrest by 4)",
    "type": "reduce",
    "expansion": "america",
    "reduce": 4
   },
   {
    "id": "red-4",
    "category": "red",
    "text": "Call for ‘extraordinary powers’ sparks bipartisan backlash.",
    "instruction": "(Choose a player to gain +-3 unrest. You gain +-1 unrest)",
    "type": "targeted",
    "expansion": "america",
    "effect": {
     "action": "chooseGain",
     "target": -3,
     "self": -1
    }
   },
   {
    "id": "red-5",
    "category": "red",
    "text": "Legislature floats alternate slates; courts respond swiftly.",
    "instruction": "(x1.5 multiplier)",
    "type": "mult",
    "expansion": "america",
    "mult": 1.5
   }
  ]
 },
 "black": [
  {
   "id": "black-0",
   "category": "black",
   "text": "March on the capitol escalates; barriers breached.",
   "instruction": "(+-5)",
   "type": "add",
   "expansion": "america",
   "add": -5
  },
  {
   "id": "black-1",
   "category": "black",
   "text": "Militias in tactical gear patrol civic spaces.",
   "instruction": "(All other players gain +-2 unrest)",
   "type": "targeted",
   "expansion": "america",
   "effect": {
    "action": "allOthers",
    "val": -2
   }
  },
  {
   "id": "black-2",
   "category": "black",
   "text": "Curfews declared across multiple cities after clashes.",
   "instruction": "(Use Card Value)",
   "type": "space",
   "expansion": "america"
  },
  {
   "id": "black-3",
   "category": "black",
   "text": "Conspiracy‑themed convoy surrounds a government complex.",
   "instruction": "(x2 multiplier)",
   "type": "mult",
   "expansion": "america",
   "mult": 2.0
  },
  {
   "id": "black-4",
   "category": "black",
   "text": "Emergency session condemns violence; de‑escalation urged.",
   "instruction": "(Reduce unrest by 6; hold and play on a future turn)",
   "type": "reduce",
   "expansion": "america",
   "reduce": 6,
   "hold": true
  },
  {
   "id": "black-5",
   "category": "black",
   "text": "Commissions investigate coordination behind the riot.",
   "instruction": "(Reduce unrest by 7)",
   "type": "reduce",
   "expansion": "america",
   "reduce": 7
  }
 ]
};
